from typing import Protocol

from .models.github import (
    PR,
    FullPR,
    PRComment,
    PRLocator,
    RepoLocator,
    Review,
    Thread,
    ThreadComment,
)
from .models.storage import StoredPR


class Store(Protocol):
    def get_pr(self, pr: PRLocator) -> FullPR | None: ...
    def store_pr(self, pr: FullPR) -> None: ...
    def get_thread(self, id: str) -> Thread | None: ...
    def get_thread_comment(self, id: str) -> ThreadComment | None: ...
    def get_threads_matching(self, id_prefix: str) -> list[Thread]: ...
    def get_thread_comments_matching(self, id_prefix: str) -> list[ThreadComment]: ...
    def get_pr_locator_for_thread(self, id: str) -> PRLocator | None: ...
    def get_pr_comment(self, id: str) -> PRComment | None: ...
    def get_review(self, id: str) -> Review | None: ...
    def get_pr_comments_matching(self, id_prefix: str) -> list[PRComment]: ...
    def get_reviews_matching(self, id_prefix: str) -> list[Review]: ...
    def get_pr_locator_for_pr_comment(self, id: str) -> PRLocator | None: ...
    def get_pr_locator_for_review(self, id: str) -> PRLocator | None: ...
    def list_prs(self) -> list[StoredPR]: ...
    def count_prs(self) -> int: ...
    def count_threads_prs(self, resolved: bool) -> tuple[int, int]: ...


class Auth(Protocol):
    def get_token(self) -> str: ...


class Forge(Protocol):
    def parse_repo(self, origin: str) -> RepoLocator: ...
    async def find_pr_for_branch(
        self, repo: RepoLocator, branch: str
    ) -> PRLocator | None: ...
    async def get_pr(self, pr: PRLocator) -> FullPR | None: ...
    async def list_repo_prs(
        self, repo: RepoLocator, closed: bool = False
    ) -> list[PR]: ...


class VCS(Protocol):
    def get_current_branch(self) -> str: ...
    def get_origin(self) -> str: ...
    def read_file(self, path: str, commit: str | None = None) -> str | None: ...
