from typing import Protocol

from .models.github import FullPR, PRLocator, RepoLocator, Thread, ThreadComment
from .models.storage import StoredPR


class Store(Protocol):
    def get_pr(self, pr: PRLocator) -> FullPR | None: ...
    def store_pr(self, pr: FullPR) -> None: ...
    def get_thread(self, id: str) -> Thread | None: ...
    def get_thread_comment(self, id: str) -> ThreadComment | None: ...
    def get_threads_matching(self, id_prefix: str) -> list[Thread]: ...
    def get_thread_comments_matching(self, id_prefix: str) -> list[ThreadComment]: ...
    def list_prs(self) -> list[StoredPR]: ...
    def count_prs(self) -> int: ...
    def count_threads_prs(self, resolved: bool) -> tuple[int, int]:
        """
        Number of resolved/unresolved threads (tuple element 0) spread across PRs (tuple element 1).
        """


class Auth(Protocol):
    def get_token(self) -> str: ...


class Forge(Protocol):
    def parse_repo(self, origin: str) -> RepoLocator: ...
    async def find_pr_for_branch(
        self, repo: RepoLocator, branch: str
    ) -> PRLocator | None: ...
    async def get_pr(self, pr: PRLocator) -> FullPR | None: ...


class VCS(Protocol):
    def get_current_branch(self) -> str: ...
    def get_origin(self) -> str: ...
